name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set the path
        run: |
          echo "path=/${{github.ref}}" >> $GITHUB_ENV
          echo "prefix=dev." >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install
      - run: npm test
      - run: npm run lint
      - run: PUBLIC_URL=$path npm run build

      - run: aws s3 cp build s3://${prefix}${{ secrets.BUCKET_NAME }}$path --recursive

      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: Check out a preview at https://dev.thelist.app/${path}!
          check_for_duplicate_msg: true
        if: github.ref != 'refs/heads/main'
